import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { ScrollToTop } from "@/components/scroll-to-top";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryProvider } from "@/lib/query-client";

import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solvro Web Template",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${space_grotesk.variable} font-sans antialiased`}>
          <Navbar />
          <div className="mx-auto max-w-7xl">
            <TooltipProvider>{children}</TooltipProvider>
          </div>
          <Footer />
          <ScrollToTop />
        </body>
      </QueryProvider>
    </html>
  );
}
